plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yuhaojun.douyinadskipper'
    compileSdkVersion 36

    defaultConfig {
        applicationId "com.yuhaojun.douyinadskipper"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 9
        versionName "0.9.0"
    }
}
